"""Add dropped file to user model

Revision ID: 9db6697972b1
Revises: dc28200ce35f
Create Date: 2020-11-26 17:48:02.326832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db6697972b1'
down_revision = 'dc28200ce35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dropped_file', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dropped_file')
    # ### end Alembic commands ###
